# Generated by Django 5.0.6 on 2026-08-23 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('atm_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=20)),
                ('cash_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOW', 'Low'), ('EMPTY', 'Empty')], default='EMPTY', max_length=20)),
                ('current_cash_balance', models.FloatField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('CURRENCY_EXCHANGE', 'Currency Exchange'), ('CHECK_DEPOSIT', 'Check Deposit')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATMService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atms.atm')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atms.service')),
            ],
            options={
                'unique_together': {('atm', 'service')},
            },
        ),
        migrations.AddField(
            model_name='atm',
            name='services',
            field=models.ManyToManyField(related_name='atms', through='atms.ATMService', to='atms.service'),
        ),
        migrations.CreateModel(
            name='HeartbeatLog',
            fields=[
                ('heartbeat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('cash_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOW', 'Low'), ('EMPTY', 'Empty')], max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='atms.atm')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['atm', '-received_at'], name='atms_heartb_atm_id_0708b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='atm',
            index=models.Index(fields=['status'], name='atms_atm_status_ee81f7_idx'),
        ),
        migrations.AddIndex(
            model_name='atm',
            index=models.Index(fields=['cash_status'], name='atms_atm_cash_st_386e76_idx'),
        ),
        migrations.AddIndex(
            model_name='atm',
            index=models.Index(fields=['latitude', 'longitude'], name='atms_atm_latitud_0c6efc_idx'),
        ),
    ]
